#pragma once

#include "engine/tracks/Track.h"
#include "engine/tracks/MarioRaceway.h"
#include "engine/tracks/ChocoMountain.h"
#include "engine/tracks/BowsersCastle.h"
#include "engine/tracks/BansheeBoardwalk.h"
#include "engine/tracks/YoshiValley.h"
#include "engine/tracks/FrappeSnowland.h"
#include "engine/tracks/KoopaTroopaBeach.h"
#include "engine/tracks/RoyalRaceway.h"
#include "engine/tracks/LuigiRaceway.h"
#include "engine/tracks/MooMooFarm.h"
#include "engine/tracks/ToadsTurnpike.h"
#include "engine/tracks/KalimariDesert.h"
#include "engine/tracks/SherbetLand.h"
#include "engine/tracks/RainbowRoad.h"
#include "engine/tracks/WarioStadium.h"
#include "engine/tracks/BlockFort.h"
#include "engine/tracks/Skyscraper.h"
#include "engine/tracks/DoubleDeck.h"
#include "engine/tracks/DKJungle.h"
#include "engine/tracks/BigDonut.h"
#include "engine/tracks/PodiumCeremony.h"
#include "engine/tracks/TestTrack.h"

